name: PinguBank
version: 1.0
main: de.pingubank
api-version: 1.20
author: Lars
description: Ein Bank-Plugin mit GUI Für Pinguino

commands:
  bank:
    description: Öffnet das Bank-GUI
  geld:
    description: Zeigt dein Kontostand
  geldbank:
    description: Zeigt dein Bankkontostand
  pay:
    description: Zahlt mit dem Kontostand an einen Spieler
    usage: /pay <Spieler> <Betrag>
  transfer:
    description: Zahlt mit dem Bankkonto an einen Spieler
    usage: /transfer <Spieler> <Betrag>
  bankfreeze:
    description: Sperrt das Bankkonto eines Spielers
    usage: /bankfreeze <Spieler>
  bankunfreeze:
    description: Entsperrt das Bankkonto eines Spielers
    usage: /bankunfreeze <Spieler>
    
